### PR TITLE
Add `selected` state to `TextMenuItem`

### PR DESCRIPTION
**Pull request by pewsheen**
Added selected methods to the `TextMenuItem` interface and  modified some examples.

I've only implemented it in macOS , so I leave todo!() in windows and unix's impl.

### CODE REVIEW

**Comment by amrbashir** [comment]
Thanks for helping out with this crate.

I don't think this is the right approach. I choose `TextMenuItem` for the default menu item name because I wanted in the future to add `SelectMenuItem`(or `CheckMenuItem`), `ImageMenuItem` and `RadioMenuItem`. This will also comply better with gtk because it doesn't allow to select `gtk::MenuItem` and have another type for that which is [`gtk::CheckMenuItem`](https://docs.gtk.org/gtk3/class.CheckMenuItem.html). cc @wusyong

**Comment by pewsheen** [comment]
> Thanks for helping out with this crate.
> 
> I don't think this is the right approach. I choose `TextMenuItem` for the default menu item name because I wanted in the future to add `SelectMenuItem`(or `CheckMenuItem`), `ImageMenuItem` and `RadioMenuItem`. This will also comply better with gtk because it doesn't allow to select `gtk::MenuItem` and have another type for that which is [`gtk::CheckMenuItem`](https://docs.gtk.org/gtk3/class.CheckMenuItem.html). cc @wusyong

Oh, ok.

This was what I thought if we keep adding things to that interface.

**Comment by wusyong** [comment]
> Thanks for helping out with this crate.
> 
> I don't think this is the right approach. I choose `TextMenuItem` for the default menu item name because I wanted in the future to add `SelectMenuItem`(or `CheckMenuItem`), `ImageMenuItem` and `RadioMenuItem`. This will also comply better with gtk because it doesn't allow to select `gtk::MenuItem` and have another type for that which is [`gtk::CheckMenuItem`](https://docs.gtk.org/gtk3/class.CheckMenuItem.html). cc @wusyong

Is it the same for windows? If so, then let's go for that. NSMenu seems more flexible than others.

**Comment by amrbashir** [comment]
Windows have the most flexible menu system of all 3 platforms so far, usually it is `gtk` that has limitations.

**Pull request closed without merging**
